import type { Metadata } from 'next'
import { adventor, proxima } from '@/assets/fonts/fonts'
import { cn } from '@/lib/utils'
import Providers from '@/components/Providers'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import './globals.css'

export const metadata: Metadata = {
  title: {
    template:
      '%s | React.js Frontend Developer | Next.js Full-Stack  Developer',
    default: 'Ilan Lavi - Berlin-based React.js Frontend Developer'
  },

  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang='en'
      suppressHydrationWarning
      className={`${adventor.variable} ${proxima.variable}`}
    >
      <body
        className={cn(
          `${`${proxima.className}`} flex min-h-screen flex-col antialiased`
        )}
      >
        <Providers>
          <Header />
          <main className='grow'>{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
